### ISSUE TITLE
Standard example where the ego_vehicle is moving

### ISSUE THREAD

**Issue by jS5t3r** [Autoware-AI/simulation#5]
Setting up the Carla environment with ROS bridge and maps is very easy now. Thank you! :+1: 

What is the easiest way to get the car moving after starting the rosbridge with manual control?

**Comment by JWhitleyWork** [comment]
@jS5t3r Please post requests for support to [ROS Answers](https://answers.ros.org/questions/scope:all/sort:activity-desc/tags:autoware/page:1/).
